### ISSUE TITLE
Gem::InstallError: rails-observers requires Ruby version >= 2.2.2.

### ISSUE THREAD

**Issue by auvilink** [InfraexDev/peatio#1]
Gem::InstallError: rails-observers requires Ruby version >= 2.2.2.
An error occurred while installing rails-observers (0.1.5), and
Bundler cannot continue.
Make sure that `gem install rails-observers -v '0.1.5'` succeeds before
bundling.

In Gemfile:
  rails-observers

**Comment by muhammednagy** [comment]
Hi
Please install ruby 2.2.2
By 
rbenv install 2.2.2
rbenv global 2.2.2
I will update the documents today

**Comment by muhammednagy** [comment]
Updated the document 
thanks for reporting the issue
Have a good day
