### ISSUE TITLE
Help solving this

### ISSUE THREAD

**Issue by samirpatelindianic** [InfraexDev/peatio#10]
Samir-Patel:peatio Samar$ bundle exec rake daemons:start
rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 6 column 3
/Users/Samar/peatio/config/application.rb:15:in `<module:Peatio>'
/Users/Samar/peatio/config/application.rb:14:in `<top (required)>'
/Users/Samar/peatio/Rakefile:5:in `require'
/Users/Samar/peatio/Rakefile:5:in `<top (required)>'
/Users/Samar/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
/Users/Samar/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
Samir-Patel:peatio Samar$ bundle exec rails server
/Users/Samar/.rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 6 column 3 (Psych::SyntaxError)
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:318:in `parse'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/2.2.0/psych.rb:245:in `load'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:60:in `parse'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:56:in `block in raw_configuration'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:56:in `yield'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:56:in `raw_configuration'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:64:in `global_configuration'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:32:in `configuration'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:42:in `each'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:36:in `load'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro.rb:23:in `load'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/figaro-1.1.1/lib/figaro/rails/railtie.rb:5:in `block in <class:Railtie>'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/lazy_load_hooks.rb:36:in `call'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.0.13/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.0.13/lib/rails/application.rb:67:in `inherited'
	from /Users/Samar/peatio/config/application.rb:15:in `<module:Peatio>'
	from /Users/Samar/peatio/config/application.rb:14:in `<top (required)>'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.0.13/lib/rails/commands.rb:74:in `require'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.0.13/lib/rails/commands.rb:74:in `block in <top (required)>'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.0.13/lib/rails/commands.rb:71:in `tap'
	from /Users/Samar/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.0.13/lib/rails/commands.rb:71:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
Samir-Patel:peatio Samar$

**Comment by muhammednagy** [comment]
Can you show me your application.yml?

**Comment by samirpatelindianic** [comment]
defaults: &defaults

  # sites hosts
  # session expire seconds
  # admin role account
  URL_HOST: localhost:3000
  URL_SCHEMA: http
  SESSION_EXPIRE: 60
  ADMIN: 'samir.patel@indianic.com,admin@peatio.dev,admin@example.com'
  TIMEZONE: 'Beijing'

  REDIS_URL: redis://127.0.0.1:6379

  # below settings only in production env
  # system notify mail settings
  # --------------------------------------------------------------
  SMTP_PORT: YOUR_SMTP_PORT
  SMTP_DOMAIN: YOUR_SMTP_DOMAIN
  SMTP_ADDRESS: YOUR_SMTP_ADDRESS
  SMTP_USERNAME: YOUR_SMTP_USERNAME
  SMTP_PASSWORD: YOUR_SMTP_PASSWORD
  SMTP_AUTHENTICATION: plain # could be plain, login or cram_md5

  SUPPORT_MAIL: support@peatio.dev
  SYSTEM_MAIL_FROM: system@peatio.dev
  SYSTEM_MAIL_TO: group@peatio.dev
  OPERATE_MAIL_TO: support@peatio.dev

  # WebSocket Streaming API settings
  # --------------------------------------------------------------
  WEBSOCKET_HOST: 0.0.0.0
  WEBSOCKET_PORT: 8080
  # Uncomment below to enable secure WebSocket (wss)
  #WEBSOCKET_SSL_KEY: 'your_server.key'
  #WEBSOCKET_SSL_CERT: 'your_server.crt'

  # pusher settings
  # --------------------------------------------------------------
  # peatio dependence Pusher (http://pusher.com) service
  # you can change your key for production environment.
  # we support development key and secret
  # uncomment below line only development or test
  #
   PUSHER_APP: 65910
   PUSHER_KEY: 50d404c35db92d736a57
   PUSHER_SECRET: 75d6e6685209cc60cc4d

  PUSHER_APP: 65910
  PUSHER_KEY: 50d404c35db92d736a57
  PUSHER_SECRET: 75d6e6685209cc60cc4d
  PUSHER_HOST: api.pusherapp.com
  PUSHER_PORT: 80
  PUSHER_WS_PORT: 80
  PUSHER_WSS_PORT: 443
  PUSHER_ENCRYPTED: true

  # twilio setting
  # --------------------------------------------------------------
  # https://github.com/twilio/twilio-ruby
  #
  TWILIO_NUMBER: YOUR_TWILIO_NUMBER
  TWILIO_SID: YOUR_TWILIO_SID
  TWILIO_TOKEN: YOUR_TWILIO_TOKEN


  # Third party auth

  # Weibo
  # --------------------------------------------------------------
  WEIBO_AUTH: on # on/off
  WEIBO_KEY: 3820920586
  WEIBO_SECRET: 2d6174dc698e86860c75d75b1e8a01c8

  # chat setting
  # --------------------------------------------------------------
  # Do you want chat feature in your exchange ?
  # send mail to community@peatio.com

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

**Comment by samirpatelindianic** [comment]
https://ufile.io/o8l5k  

link to application yaml

**Comment by muhammednagy** [comment]
https://text-share.com/view/1f36f681#L5

**Comment by muhammednagy** [comment]
you have wrong indentation
