### ISSUE TITLE
You need to create at least one account and use it as a base account for withdrawals

### ISSUE THREAD

**Issue by hostsleek** [InfraexDev/peatio#105]
Hi Mohammed.. Kindly explain this
You need to create at least one account and use it as a base account for withdrawals

Does this mean the coinbase address will be used for all ETH withdrawal. 
I have done this but still get insufficient funds when doing withdrawal

**Comment by hostsleek** [comment]
@muhammednagy

**Comment by muhammednagy** [comment]
Hi
Yes!
the idea is you need to sweep the balances from users addresses to your coinbase address or put enough funds in your coinbase address or make it forward the new ether as soon as it makes the deposit.
Regards,

**Comment by hostsleek** [comment]
Yes... That make sense.. @muhammednagy 

I am trying to implement a nodejs script that can perform this action of moving all to the coinbase address..  Do you have any information you can share. Will really appreciate.

I am also working on XRP and implementing destination tag which is almost done.. Can share that with you when done to review.
