### ISSUE TITLE
My app crashes with a “You can't use Gon public methods for storing data” 

### ISSUE THREAD

**Issue by auvilink** [InfraexDev/peatio#11]
According to the fix here https://github.com/peatio/peatio/issues/466

 The issue is with the version of Gon in either the Gemfile or Gemfile.lock.

Make sure the Gemfile has gem 'gon', '~> 5.2.0'
After bundle install, check the Gemfile.lock to make sure gon (5.2.0) is what is locked down there and not gon (5.2.3). If it is anything other than gon (5.2.0), manually change it to gon (5.2.0) in the Gemfile.lock and bundle install again and make sure you still have gon (5.2.0).
This solves it for me whenever the problem appears.

In this repository, Gemfile.lock  gon (5.2.3)
This might be the issue

**Comment by muhammednagy** [comment]
Fixed
thank you
