### ISSUE TITLE
Funds Issue

### ISSUE THREAD

**Issue by auvilink** [InfraexDev/peatio#12]
Fresh New Install.

In the funds page, if I click BTC or ETC Deposit, it still show CNY deposit, I have to manually type in the url like:

http://IP/funds#!/deposits/cny
http://IP/funds#!/deposits/BTC 
http://IP/funds#!/deposits/ETH

to get that Deposit page.

Same thing happens to the Withdraw

http://IP/funds#!/withdraws/btc

Thanks.

**Comment by shivagouraram** [comment]
I am getting this issue as well. I couldn't add any deposits from the funds page.

**Comment by muhammednagy** [comment]
it's a confirmed issue :( 
i'm working on it

**Comment by mrtass** [comment]
Im experience same behavior [issue 22](https://github.com/InfraexDev/peatio/issues/22)

**Comment by auvilink** [comment]
Any update on this?
Thanks.

**Comment by muhammednagy** [comment]
yes 
we downgraded the current version should work

**Comment by mrtass** [comment]
issue solved
