### ISSUE TITLE
Can you upgrade the Gemfile to use rails 4.2.0?

### ISSUE THREAD

**Issue by appsdev9** [InfraexDev/peatio#128]
Resolved. Thanks.

**Comment by gitgut1000** [comment]
did you manage to upgrade to 4.2.0 ?

**Comment by appsdev9** [comment]
Yes. Done.

2018-07-25 4:00 GMT+08:00 gitgut1000 <notifications@github.com>:

**Comment by gitgut1000** [comment]
any tips on that?

**Comment by appsdev9** [comment]
Delete the Gemfile.lock. Edit the Gemfile & specify certain gems version.
Run "bundle install"

2018-07-25 14:47 GMT+08:00 gitgut1000 <notifications@github.com>:

**Comment by gitgut1000** [comment]
Thanks !!
