### ISSUE TITLE
FUNDS on ETH does not show QR Code or wallet address

### ISSUE THREAD

**Issue by auvilink** [InfraexDev/peatio#13]
![eth](https://user-images.githubusercontent.com/13460230/36066165-32540d7e-0e5a-11e8-96b5-70926d853e41.jpeg)

on URL:
http://IP/funds#!/deposits/eth

**Comment by muhammednagy** [comment]
are you sure you have bitcoin and ethereum installed?

**Comment by muhammednagy** [comment]
and that peatio can communicate with them ( very important )

**Comment by auvilink** [comment]
oh, that could be the reason.
bitoind is running, so btc QR code shows ok.
installing ethereum now.

Thanks.

**Comment by muhammednagy** [comment]
you're welcome

**Comment by auvilink** [comment]
installed ethereum, now running  geth --rpc --fast on same server
Still did not see QR coder for ETH deposit,
Currencies.yml for ETH has changed as well: http://IP
all demons have been restarted
nginx has restarted as well

**Comment by auvilink** [comment]
Hi, Muhammed,


Thanks again for your great work.
 
installed ethereum, now running geth --rpc --fast on same server
Still did not see QR coder for ETH deposit,
Currencies.yml for ETH has changed as well: http://IP
all demons have been restarted
nginx has restarted as well.


I also tried to run geth like: 
geth --verbosity 3 --fast --rpc --rpcaddr=IP --rpcport=8545 --rpcapi eth,personal,net,web3


Changed Currencies.yml for ETH has changed as well: http://IP:8545
But I still did not see the QR coder for ETH deposit.


Did I miss anything here, please kindly enlighten me.


Do I have to create an account on the Ethereum server before running geth command?


Thank you so much


Michael
 
------------------ Original ------------------

**Comment by nantestdevoloper** [comment]
hi muhammednagy,

I have installed peatio on local mac.  testing fund transfer on local env. but not able to generate new address and not showing QR code
![screen shot 2018-03-07 at 11 11 37 am](https://user-images.githubusercontent.com/33446749/37076282-f2e6b9c4-21fb-11e8-8ca9-bbabea6edd21.png)

**Comment by ShivSF006** [comment]
Even I'm facing the same issue .. where u able to solve it

**Comment by muhammednagy** [comment]
hello guys 
sorry for the late reply 
so 
 i will list out all the possible reasons for not having an address 
hope it helps
1.daemons aren't running
2.peatio couldn't connect to the bitcoind ( if remote use rpcallowip in the config)
3.the rpc url in currencies.yml doesn't match with username and password in bitcoin.conf
4.there is a firewall blocking the connection
5. bitcoind isn't installed or running. :D

**Comment by nantestdevoloper** [comment]
now deployed the code on production server in real transaction mode. But still same problem.

deamons are running, rpc username password is same  in currencies.yml and bitcoin.conf
allowed bitcoind port number to access.
I installed all depepndent server on same IP. There is enough space also.
