### ISSUE TITLE
E, [2018-02-10T11:39:53.664244 #76958] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)

### ISSUE THREAD

**Issue by auvilink** [InfraexDev/peatio#14]
Fresh New Installation
Ubuntu 16.04
8GB Ram

E, [2018-02-10T11:39:53.664052 #76958] ERROR -- : read would block (OpenSSL::SSL::SSLErrorWaitReadable)

E, [2018-02-10T11:39:53.664244 #76958] ERROR -- : Resource temporarily unavailable - read would block (IO::EAGAINWaitReadable)

**Comment by muhammednagy** [comment]
more details?

**Comment by auvilink** [comment]
I did not enable openssl in production.rb
I did not install SSL certificate
Just installed the peatio using latest repository, checking output from peatio:amqp:notification.log

**Comment by muhammednagy** [comment]
that's  an expected behaviour 
https://stackoverflow.com/questions/30669667/ioeagainwaitreadable-resource-temporarily-unavailable-read-would-block

**Comment by auvilink** [comment]
E, [2018-02-10T11:39:53.664052 #76958] ERROR -- : read would block (OpenSSL::SSL::SSLErrorWaitReadable)

So this is also expected, I assume.

**Comment by muhammednagy** [comment]
i think so 
OpenSSL is used somewhere there as a library 
i don't know for sure what's the reason

**Comment by prototypensx** [comment]
Try and update Openssl for both Ruby and Ubuntu, it's used by both. 
read here 
https://stackoverflow.com/questions/11059059/is-it-possible-to-enable-tls-v1-2-in-ruby-if-so-how

https://stackoverflow.com/questions/22993541/how-can-i-ensure-that-ruby-uses-an-openssl-not-vulnerable-to-heartbleed?noredirect=1&lq=1

https://stackoverflow.com/questions/13956134/how-to-tell-which-openssl-lib-is-actually-being-used-by-an-rvm-installed-ruby

**Comment by muhammednagy** [comment]
We can update once we upgrade the rails and ruby version 
they update dynamically
