### ISSUE TITLE
New coin address generating

### ISSUE THREAD

**Issue by istiaqiut** [InfraexDev/peatio#16]
Hi,
In your currencies.yml.example, you have mentioned 
`  rpc: http://Your_eth_server_ip`
what will be that address?
I am trying  
`rpc: http://username:password@127.0.0.1:18332`
but my coin address is not generated.
Do I need to change any other files?
Thanks.

**Comment by muhammednagy** [comment]
HI
i've mentioned that for ETH not BTC 
you have mixed them up

**Comment by istiaqiut** [comment]
How can I find my eth_server_ip?
