### ISSUE TITLE
bundle install fails 

### ISSUE THREAD

**Issue by anibha88** [InfraexDev/peatio#17]
Hi,
when I run bundle install --without development test --path vendor/bundle
It fails giving below error:
Can someone please suggest how to fix this?

Below is the error log:
The git source `git://github.com/peatio/unread.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
The git source `git://github.com/peatio/mina-slack.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/peatio/unread.git
fatal: remote error: 
  Repository not found.

Retrying `git clone 'git://github.com/peatio/unread.git' "/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/cache/bundler/git/unread-6a6d2cdc81f7aab935ed08372c65417ce6196e67" --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/peatio/unread.git' "/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/cache/bundler/git/unread-6a6d2cdc81f7aab935ed08372c65417ce6196e67" --bare --no-hardlinks --quiet` in directory /home/ubuntu/peatio/current has failed.fatal: remote error: 
  Repository not found.

Retrying `git clone 'git://github.com/peatio/unread.git' "/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/cache/bundler/git/unread-6a6d2cdc81f7aab935ed08372c65417ce6196e67" --bare --no-hardlinks --quiet` due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/peatio/unread.git' "/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/cache/bundler/git/unread-6a6d2cdc81f7aab935ed08372c65417ce6196e67" --bare --no-hardlinks --quiet` in directory /home/ubuntu/peatio/current has failed.fatal: remote error: 
  Repository not found.

Retrying `git clone 'git://github.com/peatio/unread.git' "/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/cache/bundler/git/unread-6a6d2cdc81f7aab935ed08372c65417ce6196e67" --bare --no-hardlinks --quiet` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'git://github.com/peatio/unread.git' "/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/cache/bundler/git/unread-6a6d2cdc81f7aab935ed08372c65417ce6196e67" --bare --no-hardlinks --quiet` in directory /home/ubuntu/peatio/current has failed.fatal: remote error: 
  Repository not found.

Git error: command `git clone 'git://github.com/peatio/unread.git'
"/home/ubuntu/peatio/current/vendor/bundle/ruby/2.2.0/cache/bundler/git/unread-6a6d2cdc81f7aab935ed08372c65417ce6196e67" --bare --no-hardlinks --quiet` in directory
/home/ubuntu/peatio/current has failed.

**Comment by rainsom** [comment]
Yes, i got the same error msg with you when i try to run this code below:

＃ Install dependency gems
bundle install --without development test --path vendor/bundle

**Comment by muhammednagy** [comment]
that just doesn't make sense if you use the latest version of this code 
because i already updated this in the Gemfile

**Comment by anibha88** [comment]
Hi @muhammednagy 
I just followed step by step as given here
https://github.com/InfraexDev/peatio/blob/master/doc/deploy-production-server.md

**Comment by muhammednagy** [comment]
okay give me a moment to update the documents to point to this repo instead of the old repo

**Comment by rainsom** [comment]
@anibha88 @muhammednagy I managed to solved the issue with update the latest Gemfile and run the bundle install again.

**Comment by anibha88** [comment]
Thanks @muhammednagy and @rainsom !
