### ISSUE TITLE
RAILS_ENV=production rake solvency:liability_proof  ERROR

### ISSUE THREAD

**Issue by auvilink** [InfraexDev/peatio#28]
rake aborted!
Gem::LoadError: You have already activated rake 10.4.2, but your Gemfile requires rake 12.3.0. Since rake is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports rake as a default gem.
/home/deploy/peatio/current/config/boot.rb:6:in `<top (required)>'
/home/deploy/peatio/current/config/application.rb:1:in `<top (required)>'
/home/deploy/peatio/current/Rakefile:5:in `<top (required)>'
LoadError: cannot load such file -- bundler/setup
/home/deploy/peatio/current/config/boot.rb:6:in `<top (required)>'
/home/deploy/peatio/current/config/application.rb:1:in `<top (required)>'
/home/deploy/peatio/current/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)

**Comment by muhammednagy** [comment]
you need to use RAILS_ENV=production bundle execrake solvency:liability_proof

**Comment by auvilink** [comment]
Thanks, problem solved.

**Comment by auvilink** [comment]
BTW, this will only show BTC / CNY solvency, right? I did not see solvency for ETH.
