### ISSUE TITLE
Git error: command `git clone 'git://github.com/peatio/unread.git'

### ISSUE THREAD

**Issue by ilerrajtadros** [InfraexDev/peatio#3]
I get this error **Git error: command `git clone 'git://github.com/peatio/unread.git'** on the bundle install step. Can you help me with that?

**Comment by muhammednagy** [comment]
hello 
for some unknown reasons peatio team removed unread repo from github and this prevents people from using the project
but don't worry we published it again

**Comment by ilerrajtadros** [comment]
There is another peatio repo too in the Gemfile, it seems to have been
removed too

**Comment by muhammednagy** [comment]
yeah mina-slack

**Comment by ilerrajtadros** [comment]
Great, it is restored too?

**Comment by muhammednagy** [comment]
yes
