### ISSUE TITLE
Problem generating a new bitcoin address

### ISSUE THREAD

**Issue by founds** [InfraexDev/peatio#35]
Hello,
I have the problem that the field of generating a new bitcoin address appears blank.
I used production and daemons all start.
say:
"it can't generate new address if it hasn't been used."
thanks very much

**Comment by frezeq0** [comment]
bittrex opensource: https://github.com/frezeq0/bittrex-opensource

**Comment by founds** [comment]
I solved add to .bitcoin/bitcoin.conf
"rpcallowip=LOCAL IP"

**Comment by muhammednagy** [comment]
Oh
It should work without the need for that
Internal process can connect with bitcoind without allowing IPs
