### ISSUE TITLE
"Funds" not working

### ISSUE THREAD

**Issue by Mishul-G** [InfraexDev/peatio#36]
Whenever I try to access the "Funds" page, I get redirected to localhost:3000/settings

I see other people have this problem too but no one has directly written a solution regarding this. We have our google authenticator setup for 2FA. Another Problem - our mobile phone does not work for verification.

We are trying to setup a demo to demonstrate trades on the platform - is there a way around this? Would appreciate help in this as well.

Thank you.

**Comment by frezeq0** [comment]
bittrex opensource: https://github.com/frezeq0/bittrex-opensource

**Comment by frezeq00** [comment]
bittrex opensource: https://github.com/pkdcryptos/frezeq0_bittrex-opensource

**Comment by alibowling** [comment]
you need open to config/application.yml file then change "host: localhost:3000" with your host name
