### ISSUE TITLE
bundle exec rake db:setup error 

### ISSUE THREAD

**Issue by dru0** [InfraexDev/peatio#37]
System Ubuntu 16.04.4 LTS
ruby 2.2.2p95
Install ruby from readme
https://github.com/InfraexDev/peatio/blob/stable/doc/setup-local-ubuntu.md
and 
echo "gem: --no-ri --no-rdoc" > ~/.gemrc
gem install bundler
rbenv rehash
bundle install --without development test --path vendor/bundle

bundle exec rake db:setup --trace

peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-1.1.1/lib/figaro/application.rb:84:in `non_string_configuration!' : WARNING: Use strings for Figaro configuration. 3820920586 was converted to "3820920586". (StructuredWarnings::StandardWarning)
** Invoke db:setup (first_time)
** Invoke db:schema:load_if_ruby (first_time)
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:create
** Invoke environment (first_time)
** Execute environment
rake aborted!
NameError: uninitialized constant ActiveRecord::Type
/home/.../peatio/current/vendor/bundle/ruby/2.2.0/gems/enumerize-2.2.1/lib/enumerize/activerecord.rb:69:in `<module:ActiveRecordSupport>'
/home/.../peatio/current/vendor/bundle/ruby/2.2.0/gems/enumerize-2.2.1/lib/enumerize/activerecord.rb:2:in `<module:Enumerize>'
/home/.../peatio/current/vendor/bundle/ruby/2.2.0/gems/enumerize-2.2.1/lib/enumerize/activerecord.rb:1:in `<top (required)>'
/home/.../peatio/current/vendor/bundle/ruby/2.2.0/gems/enumerize-2.2.1/lib/enumerize.rb:40:in `extended'
/home/.../peatio/current/app/models/deposit.rb:4:in `extend'
/home/.../peatio/current/app/models/deposit.rb:4:in `<class:Deposit>'
/home/.../peatio/current/app/models/deposit.rb:1:in `<top (required)>'
/home/.../peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.13/lib/active_support/inflector/methods.rb:226:in `const_get'

**Comment by frezeq0** [comment]
bittrex opensource: https://github.com/frezeq0/bittrex-opensource

**Comment by frezeq00** [comment]
bittrex opensource: https://github.com/pkdcryptos/frezeq0_bittrex-opensource

**Comment by muhammednagy** [comment]
you need ruby 2.2.1
not 2.2.2
