### ISSUE TITLE
rake aborted! NameError: uninitialized constant ActiveRecord::Type /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/enumerize-2.1.2/lib/enumerize/activerecord.rb:69:in `<module:ActiveRecordSupport>'

### ISSUE THREAD

**Issue by auvilink** [InfraexDev/peatio#4]
Hi, muhammednagy,

Thank you so much for your great work.

My system: 
Ubuntu 16.04, freshly installed, using ruby 2.2.2 as you suggested.

using git://github.com/InfraexDev/peatio.git

I have some issues when doing : bundle exec rake db:setup

rake aborted!
NameError: uninitialized constant ActiveRecord::Type
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/enumerize-2.1.2/lib/enumerize/activerecord.rb:69:in `<module:ActiveRecordSupport>'

Thank you.

**Comment by muhammednagy** [comment]
hello can you try again and let me know?

**Comment by muhammednagy** [comment]
i tested locally 
the problem seems to be solved 
the server worked normally and everything is just normal 
i saw the notices in the console 
i will update them tomorrow after my exam :) 
thank you and please keep reporting and i will keep fixing

**Comment by auvilink** [comment]
Yes, I just tested it and it works!!!
Thank you so much.
