### ISSUE TITLE
What is https://yourwebsite.com/webhooks/eth in service.rb for eth

### ISSUE THREAD

**Issue by shivagouraram** [InfraexDev/peatio#42]
hi Guys,

It looks like I almost setup ETH for Peatio, could generate addresses from the app but couldn't get the balance for that address. It looks like I did wrong config in service.rb. Could you please let us know what should be the below URL replaced with? at the moment I updated with my server URL but looks like it is different that what I expected. 

https://yourwebsite.com/webhooks/eth

**Comment by muhammednagy** [comment]
that's the url for the webhook that let's the exchange know about new txs

**Comment by shivagouraram** [comment]
Thanks Nagy, could you let me know whether the URL should point to local IP or the actual blockchain URL.
Ex: https://rinkeby.etherscan.io/tx/0x52ce2d8575b2bdadb3144da4235e3f522e1333345c065180fcbdde98112922

**Comment by shivagouraram** [comment]
got it. I see a webhooks controller. not sure how I missed looking at it first.

**Comment by mrtass** [comment]
im facing same issue with ETH setup
would u mind share ur findings ?

**Comment by shivagouraram** [comment]
for me, I believe app couldn't sync the transactions with the database and hence cannot update the balance. at the moment, it looks like incorrect URL configuration in service.rb where I inserted a incorrect URL. I have to try update it and see if there is anything else apart from it.
