### ISSUE TITLE
ETH Integration help

### ISSUE THREAD

**Issue by riddlez666** [InfraexDev/peatio#45]
Please i need assistance we are very close but just need some tips to get this working.

**Comment by muhammednagy** [comment]
can you list the current problems?

**Comment by riddlez666** [comment]
cant generate address

**Comment by jal3inc** [comment]
Hi there, Riddlez and I are on the same team. Current problem we are having is with eth. From the deposit funds page we are able to generate a new address within the geth instance but the info doesnt not seem to be saving properly on the exchange side. Here is our current error when generating a address. `I, [2018-03-09T13:46:00.578930 #13894]  INFO -- : Received: {"payment_address_id":10,"currency":"eth","locale":"en"}
F, [2018-03-09T13:46:01.017531 #13894] FATAL -- : {"code"=>-32601, "message"=>"The method personal_newAccount does not exist/is not available"} (CoinRPC::JSONRPCError)
/home/deploy/peatio/current/app/services/coin_rpc.rb:62:in `handle'
/home/deploy/peatio/current/app/services/coin_rpc.rb:23:in `method_missing'
/home/deploy/peatio/current/app/models/worker/deposit_coin_address.rb:12:in `process'
/home/deploy/peatio/current/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'
F, [2018-03-09T13:46:01.017636 #13894] FATAL -- : /home/deploy/peatio/current/app/services/coin_rpc.rb:62:in `handle'
/home/deploy/peatio/current/app/services/coin_rpc.rb:23:in `method_missing'
/home/deploy/peatio/current/app/models/worker/deposit_coin_address.rb:12:in `process'
/home/deploy/peatio/current/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'`

**Comment by jal3inc** [comment]
Also within the the browser console I can see a 403 error that is being created by the cntrl_coinable.rb

**Comment by riddlez666** [comment]
@muhammednagy

**Comment by muhammednagy** [comment]
Can you make sure you have the personal API enabled?

**Comment by riddlez666** [comment]
screen -dmS ethgeth /usr/bin/geth --rpc --unlock  --password=".eth_pass" --rpcaddr=0.0.0.0 --rpcport=8545 --rpcapi eth,personal,net,web3,db

**Comment by riddlez666** [comment]
we have it set in the startup...

**Comment by osoese** [comment]
@muhammednagy running geth on a seperate server than exchange (I am on the same team with @jal3inc and @riddlez666 )

**Comment by muhammednagy** [comment]
hello guys :D 
@osoese @riddlez666  @jal3inc

**Comment by muhammednagy** [comment]
do you have nginx forwarding or are you trying to connect directly to geth?

**Comment by jal3inc** [comment]
We have been going nuts @muhammednagy thank you for assisting us :)

**Comment by jal3inc** [comment]
Same config file as in your project

**Comment by muhammednagy** [comment]
did it work?

**Comment by jal3inc** [comment]
yes because when gen address from exchange geth creates new address... but doesnt forward the info back to exchange

**Comment by muhammednagy** [comment]
why?

**Comment by jal3inc** [comment]
![image](https://user-images.githubusercontent.com/24689265/37212013-d31807ca-237b-11e8-9568-6f8929bca63a.png)

**Comment by jal3inc** [comment]
![image](https://user-images.githubusercontent.com/24689265/37212091-14d11db4-237c-11e8-9a97-6010153eb9e4.png)

**Comment by muhammednagy** [comment]
oh okay 
so generate address shouldn't work if you didn't use your address
Explanation : the first time it tries to get an address it sets it if it failed it considers it as an address 
you need to use your address first to get a new one

**Comment by jal3inc** [comment]
this address would be the first address we created within geth and funded... 
0xc9b0d49ddea1a38da1269d1fb54244ddb07d5241

**Comment by muhammednagy** [comment]
open bin/rails c
PaymentAddress.where(currency: "eth")

show me the output

**Comment by jal3inc** [comment]
![image](https://user-images.githubusercontent.com/24689265/37212267-8f9fb64a-237c-11e8-95c8-549922996263.png)

**Comment by muhammednagy** [comment]
oh 
that's weird

**Comment by jal3inc** [comment]
Exactly haha

**Comment by muhammednagy** [comment]
you must have done something weird or worng
can you tell me what did you do from the beginning of installing peatio
also show me bundle exec rake daemons:status

**Comment by jal3inc** [comment]
Have followed your instructions. Possible something has been over looked but honestly I cannot find. 
![image](https://user-images.githubusercontent.com/24689265/37212529-3777c7d6-237d-11e8-9f50-010d06acfb6a.png)

**Comment by jal3inc** [comment]
Also the Pusher api ... It must be in the Mnt1 cluster in order for pusher to work learned that the hard way too.

**Comment by jal3inc** [comment]
Would you be willing to to communicate with us directly and possibly remote connect to us to have a look around? I am sure with your expertise the problem would probably stand out rather quickly for you.

**Comment by muhammednagy** [comment]
okay
