### ISSUE TITLE
Add Litecoin Support

### ISSUE THREAD

**Issue by auvilink** [InfraexDev/peatio#49]
This might be a tough task.

I am trying to add litecoin to this fork based on 
https://github.com/InfraexDev/peatio/blob/stable/doc/currency.md

The last part, I copied 
deposits_litecoins POST /deposits/litecoins(.:format) private/deposits/litecoins#create
new_deposits_litecoin GET /deposits/litecoins/new(.:format) private/deposits/litecoins#new

to the end of  config/router.rb

I have received multiple errors when I do 

bundle exec rake assets:precompile

Errors like:
routes.rb:129: unknown regexp options - ltc
routes.rb:129: syntax error, unexpected '(', expecting keyword_end
...coins POST /deposits/litecoins(.:format) private/deposits/li...

If anyone has successfully done this, could you please paste the router.rb code? 

Or maybe this piece of code should be added to some other files?

Thank you so much.

**Comment by auvilink** [comment]
Looks like nobody knows the answer?

**Comment by muhammednagy** [comment]
this document is basically wrong

**Comment by auvilink** [comment]
@muhammednagy 
No wonder it does not work. Any chance you could kindly correct the document?
Thanks.

**Comment by mrtass** [comment]
@auvilink check this out
https://gist.github.com/muhammednagy/e2ac3e576216ebf576664f43e2f60002

**Comment by muhammednagy** [comment]
i totally forgot about this gist 
Thank you @mrtass

**Comment by auvilink** [comment]
Thanks guys, I'll try that.
