### ISSUE TITLE
Withdraw fees for all coins always come out as 0.0001

### ISSUE THREAD

**Issue by dfletcher** [InfraexDev/peatio#5]
Hello. I have inherited a peatio installation that comes from the muhammednagy/peatio version of the repository.

The issue is when making withdraws, the fee is always 0.0001 as in the `set_fee` function from app/models/concerns/withdraws/coinable.rb The 'fee' values from config/withdraw_channels.yml are ignored entirely.

For example, i have the Dogecoin fee set to 2.0 in withdraw_channels.yml but making a withdraw from the peatio install always uses 0.0001. Sometimes this transaction itself fails with a "fee too low" message. Other times it goes through but shows an actual 0.0001 fee on the blockchain, as well as on my peatio funds page.

Is this a known issue from an older code base and I should update to master branch here? Or has anyone else seen a similar problem and knows what could cause this?

Edit: if I change the hard-coded value in app/models/concerns/withdraws/coinable.rb then the fee value does change. So this is certainly where it's coming from. I don't understand why it's not picking up the withdraw_channel.yml setting when creating a Withdraw object.

**Comment by muhammednagy** [comment]
fixed !
Thank you for reporting

**Comment by dfletcher** [comment]
Hello @muhammednagy thanks for the quick response. This fix however is wrong, breaks several aspects of the withdraw code, and I suspect it also breaks audits.

The place where you put the fix - in the code immediately above the RPC withdrawing code - is clearly not the right place to do this. The value you changed is ignored in `calc_fee` function in app/models/withdraw.rb which subtracts the fee from the withdraw amount. It is also ignored by the UI which reports the fee as 0.0001 still, and ignored by the database code which doing a manual SELECT shows 0.0001000000000000 in the fee field of the withdraw table.

So this withdraws more coin than expected. By way of example, I told it to withdraw 3 doge with a 2 doge fee. The UI shows me "2.9999 doge sent, 0.0001 fee". Dogechain says it sent me 2.9999 with a 2 doge fee. So 4.9999 was withdrawn and peatio only sees 3 of it. That's bad.

**Comment by muhammednagy** [comment]
what do you think of adding `self.fee = withdraw.channel.fee.to_d
` in set_fee in app/models/concerns/withdraws/coinable.rb

**Comment by dfletcher** [comment]
>what do you think of adding self.fee = withdraw.channel.fee.to_d in set_fee in app/models/concerns/withdraws/coinable.rb

I tried that. actually what I did was copy the line from the function you changed which said something like `withdraw.channel.try(:fee).to_d` which inside coinable.rb would actually come out as (I think!) `self.channel.try(:fee)`. I tried printing self.channel to the log from there and it looks legit. However that code is called from 2 different contexts - from the website (I assume when you actually clicked the withdraw submit button) ... but also from the withdraw_coin daemon. When called from withdraw_coin it doesn't seem to work correctly (because Rails isn't bootstrapped?). Anyway, all attempts I've made at altering this function seem to cause withdraw to fail entirely. When this happens the withdraw is stuck in "almost_done" state but never completes. Unsure why.

This brings up another point - are you actually testing quick withdraws here? Because I can see that the code of app/models/withdraw.rb audit! function does not contain my fix (sorry I commented on the original peatio project about that, not your fork) https://github.com/peatio/peatio/issues/493#issuecomment-337458173 ... so I'm wondering if anyone at all is actually paying attention to coin withdraws in this project. And that is very worrying, it seems like having that work correctly is critical for users to feel comfortable using the software.

**Comment by muhammednagy** [comment]
okay 
 i will do heavy testing and debugging on that and let you know 
i will also push your quick transaction fix

**Comment by muhammednagy** [comment]
@dfletcher  can you ping me on my mail?
me [at]  muhnagy.com

**Comment by ParthBarot-BoTreeConsulting** [comment]
Did you find any solution to this?
