### ISSUE TITLE
Deposit ETH not showing in balance

### ISSUE THREAD

**Issue by auvilink** [InfraexDev/peatio#52]
Hi, Muhammednagy,

I have deposited some ETH to the account, it is verified on etherscan.io but does not show up in the peatio ETH account balance.

I have followed the instruction setting up ETH server and have no problem generating ETH address for deposit.

Thanks.

**Comment by muhammednagy** [comment]
please check service.rb

**Comment by auvilink** [comment]
on ETH server,

 service filter status
● filter.service - filter
   Loaded: loaded (/etc/systemd/system/filter.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2018-03-18 19:18:54 UTC; 5h 32min ago
 Main PID: 12128 (ruby)
    Tasks: 10
   Memory: 31.4M
      CPU: 3h 36min 34.566s
   CGroup: /system.slice/filter.service
           └─12128 /usr/bin/ruby /home/xxx/service.rb

Does that mean service.rb is working?

in service.rb:
postData = Net::HTTP.post_form(URI.parse('https://exchangexx.com/webhooks/eth'),.......

Problem still not resolved though.

Thank you.

**Comment by hostsleek** [comment]
@auvilink were you able to make this work?
I am having similar issue.
