### ISSUE TITLE
No route matches [GET] "/webhooks

### ISSUE THREAD

**Issue by auvilink** [InfraexDev/peatio#55]
I, [2018-03-18T23:26:52.842217 #18802]  INFO -- : Processing by Private::FundsController#index as HTML
I, [2018-03-18T23:26:52.865630 #18802]  INFO -- :   Rendered private/funds/index.html.erb within layouts/funds (0.2ms)
I, [2018-03-18T23:26:52.870734 #18802]  INFO -- :   Rendered shared/_html5.html.slim (0.1ms)
I, [2018-03-18T23:26:52.871306 #18802]  INFO -- :   Rendered shared/_meta.html.slim (0.4ms)
I, [2018-03-18T23:26:52.874591 #18802]  INFO -- :   Rendered shared/_header_profile_setting.html.slim (2.0ms)
I, [2018-03-18T23:26:52.874828 #18802]  INFO -- :   Rendered shared/_header_lang_sel.html.slim (0.1ms)
I, [2018-03-18T23:26:52.874910 #18802]  INFO -- :   Rendered shared/_header.html.slim (3.4ms)
I, [2018-03-18T23:26:52.875076 #18802]  INFO -- :   Rendered shared/_footer.html.slim (0.0ms)
I, [2018-03-18T23:26:52.875264 #18802]  INFO -- : Completed 200 OK in 33ms (Views: 9.9ms | ActiveRecord: 3.5ms)
I, [2018-03-18T23:26:53.323226 #18802]  INFO -- : Started POST "/funds/gen_address" for xx.xx.67.75 at 2018-03-18 23:26:53 +0000
I, [2018-03-18T23:26:53.324407 #18802]  INFO -- : Processing by Private::FundsController#gen_address as */*
I, [2018-03-18T23:26:53.336678 #18802]  INFO -- :   Rendered text template (0.0ms)
I, [2018-03-18T23:26:53.336860 #18802]  INFO -- : Completed 200 OK in 12ms (Views: 0.4ms | ActiveRecord: 1.6ms)
I, [2018-03-18T23:26:56.272382 #27793]  INFO -- :
Sent mail to xx@xx.com (3470.3ms)
I, [2018-03-18T23:27:28.813258 #18802]  INFO -- : Started GET "/webhooks" for xx.xx.67.75 at 2018-03-18 23:27:28 +0000
F, [2018-03-18T23:27:28.815425 #18802] FATAL -- :
ActionController::RoutingError (No route matches [GET] "/webhooks"):
  lib/middleware/security.rb:11:in `call'

This is the output from production.log, could be the reason ETH deposit not working well.

filter.service - filter
   Loaded: loaded (/etc/systemd/system/filter.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2018-03-18 19:18:54 UTC; 5h 32min ago
 Main PID: 12128 (ruby)
    Tasks: 10
   Memory: 31.4M
      CPU: 3h 36min 34.566s
   CGroup: /system.slice/filter.service
           └─12128 /usr/bin/ruby /home/xx/service.rb

This is the output from GETH server when issue "service filter status"

service.rb

postData = Net::HTTP.post_form(URI.parse('https://exchangexx.com/webhooks/eth'),.......

Thank you for your help

**Comment by muhammednagy** [comment]
it should be /webhooks/eth not /webhooks
