### ISSUE TITLE
Where are GETH (ETH) accounts stored?

### ISSUE THREAD

**Issue by auvilink** [InfraexDev/peatio#56]
Setup a dedicated ETH server using the instruction. No problem getting ETH address in peatio.

I have 3 testing users on peatio, each has it's own ETH address.
However, on the ETH server, when I issue command "geth account list", only the base ETH account/address (the one listed in config/currencies.yml) listed.

What happened to other users's ETH account/address? Where are they stored?

Thank you.

**Comment by muhammednagy** [comment]
go to the server under root user
do
geth attach
eth.accounts 
and you will get the list

**Comment by auvilink** [comment]
Thank you so much. I can see all the accounts now.
