### ISSUE TITLE
AMQ::Protocol::EmptyResponseError: Empty response received from the server

### ISSUE THREAD

**Issue by aaron-guoyx** [InfraexDev/peatio#59]
Hi, could you help with this issue?

AMQ::Protocol::EmptyResponseError: Empty response received from the server.
from /home/dev/.rvm/gems/ruby-2.2.1/gems/amq-protocol-1.9.2/lib/amq/protocol/frame.rb:60:in `decode_header'

It seems something wrong with bunny and rabbitmq connection.

Thanks

**Comment by muhammednagy** [comment]
can you give me more info?
this never happened with me 
is rabbitmq up?
are you trying to setup them on a separate servers?

**Comment by aaron-guoyx** [comment]
I set up the project in Ubuntu as described in the documentation. Rabbitmq is running as I can open rabbitmq_management console which is localhost:15672. However, only exchanges are found here. There is no queues. I also attached a snapshot.
![screenshot from 2018-03-22 10-07-21](https://user-images.githubusercontent.com/36910091/37742245-f07c63c8-2db8-11e8-87a3-83e6f37a582a.png)
![screenshot from 2018-03-22 10-07-05](https://user-images.githubusercontent.com/36910091/37742247-f0b39cc6-2db8-11e8-8227-9316e9dd3b73.png)


The back trace is as follows:
/home/dev/.rvm/gems/ruby-2.2.1/gems/amq-protocol-1.9.2/lib/amq/protocol/frame.rb:60:in `decode_header': Empty response received from the server. (AMQ::Protocol::EmptyResponseError)
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/transport.rb:208:in `read_next_frame'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/session.rb:923:in `init_connection'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/session.rb:254:in `start'
	from /home/dev/Aaron/acx/lib/daemons/amqp_daemon.rb:18:in `<top (required)>'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
	from /home/dev/.rvm/gems/ruby-2.2.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
	from lib/daemons/matching_ctl:11:in `<main>'
peatio:amqp:matching: process with pid 5539 started.

**Comment by aaron-guoyx** [comment]
So I also suspect it might have something with bunny. Thanks

**Comment by aaron-guoyx** [comment]
only on my local machine

**Comment by aaron-guoyx** [comment]
Does that have something to do with the rabbitmq? My rabbitmq only has 15672 port

**Comment by muhammednagy** [comment]
yes it's rabbitmq
did you change anything related to it?

**Comment by aaron-guoyx** [comment]
Hi, I already fixed it.

It's port configuration problem.

Thanks


Kind Regards,

Aaron Guo

Software Developer

Mobile:         +61 431 778 768

Office:          1300 88 38 48

Address:      Level 1, 89-91 City Rd

                     Southbank, VIC 3006

Web:             www.blockchainglobal.com

Disclaimer: This email has been sent on the condition that the
recipient/client agrees and acknowledges that the email may contain
material that is confidential and/or covered by legal professional
privilege and is intended for the named recipient. Blockchain Global Ltd
does not warrant that the contents of any electronically transmitted
information is accurate and will remain confidential. If the reader of this
email is not the intended recipient you are hereby notified that any use,
reproduction, disclosure or distribution of the information contained in
the email is prohibited. If you receive this email in error, please reply
to the sender immediately and delete the document. No warranty is made that
this material is free from computer virus or any other defect or error.

**Comment by aaron-guoyx** [comment]
Already fixed it.
Thanks

**Comment by aaron-guoyx** [comment]
Already fixed it.
Thanks
