### ISSUE TITLE
Bitcoin Withdraw always says:  "Almost done"

### ISSUE THREAD

**Issue by auvilink** [InfraexDev/peatio#62]
![withdraw_almost_done](https://user-images.githubusercontent.com/13460230/37741293-096068bc-2d1e-11e8-9580-285941b12bbf.jpg)

What does this suppose to mean?

Thanks.

**Comment by auvilink** [comment]
In withdraw_coin.output

F, [2018-03-21T22:34:37.329507 #13850] FATAL -- : /home/deploy/peatio/current/app/models/worker/withdraw_coin.rb:20:in `block in process'

Could this be the reason?

**Comment by mrtass** [comment]
means ur transaction is waiting for confirmations from bitcoin servers.
just wait .... in the mean time u can check bitcoin daemon is running and transaction received ...

**Comment by auvilink** [comment]
It's been like this (Almost done) all day.
The balance is still in the peatio hot-wallet, but being locked.
The recipient did not receive the bitcoin.

All daemons are running

**Comment by auvilink** [comment]
In peatio\:amqp\:withdraw_coin.output

peatio:amqp:withdraw_coin: process with pid 13850 started.
I, [2018-03-21T22:16:33.927152 #13850]  INFO -- : Connected to AMQP broker (prefetch: default)
I, [2018-03-21T22:34:37.187691 #13850]  INFO -- : Received: {"id":2,"locale":"en"}
F, [2018-03-21T22:34:37.329391 #13850] FATAL -- : undefined local variable or method `currency' for #<Worker::WithdrawCoin:0x0056156223f398> (NameError)
/home/deploy/peatio/current/app/models/worker/withdraw_coin.rb:20:in `block in process'

This could be the reason.

**Comment by mrtass** [comment]
do a tailf ~/.bitcoin/testnet/debug.log 

and show log line with progress

**Comment by auvilink** [comment]
I am not on the testnet, anyway, tried with tailf ~/.bitcoin/debug.log and below are the output

2018-03-22 15:51:11 connect() to 5.76.213.40:8333 failed after select(): Connection refused (111)
2018-03-22 15:52:04 connect() to 77.37.236.232:8333 failed after select(): No route to host (113)
2018-03-22 15:54:17 UpdateTip: new best=00000000000000000011e2d1c501f8f0f0043bca833b89fef449e6f0f92961c4 height=514689 version=0x20000000 log2_work=88.41141 tx=306148639 date='2018-03-22 15:53:46' progress=1.000000 cache=48.0MiB(120484txo)
2018-03-22 15:56:27 UpdateTip: new best=00000000000000000000942cc0d43f2addb87132c6e44788a04999ff6c209669 height=514690 version=0x20000000 log2_work=88.411462 tx=306149164 date='2018-03-22 15:55:46' progress=1.000000 cache=48.1MiB(121432txo)
2018-03-22 16:08:07 UpdateTip: new best=0000000000000000000e05f8936709f09c42f05081f9c0728494e9555e1e8dee height=514691 version=0x20000000 log2_work=88.411514 tx=306151120 date='2018-03-22 16:07:50' progress=1.000000 cache=48.7MiB(126301txo)
2018-03-22 16:12:13 connect() to 116.6.112.98:8333 failed after select(): Connection refused (111)
2018-03-22 16:13:19 connect() to [2001:56a:72e0:ae00:e9:2fda:4c6d:4406]:8333 failed: Network is unreachable (101)
2018-03-22 16:16:46 UpdateTip: new best=000000000000000000466336c7338abb84ad8e774d6398b60059ddcd47ca2468 height=514692 version=0x20000000 log2_work=88.411566 tx=306152483 date='2018-03-22 16:16:12' progress=1.000000 cache=49.1MiB(130097txo)
2018-03-22 16:27:17 UpdateTip: new best=00000000000000000029d89c46cb9bf4fd2ef109428cd51cc41b9572f497d0b8 height=514693 version=0x20000000 log2_work=88.411618 tx=306153913 date='2018-03-22 16:27:16' progress=1.000000 cache=49.6MiB(133804txo)
2018-03-22 16:34:14 UpdateTip: new best=000000000000000000151208f69170d64b7af1da7f2ad7eb02a4a463cb958f41 height=514694 version=0x20000000 log2_work=88.41167 tx=306155145 date='2018-03-22 16:34:30' progress=1.000000 cache=50.1MiB(137617txo)

**Comment by mrtass** [comment]
ok great in that case search for ur withdrawal transaction id on blockchain.com

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by auvilink** [comment]
It seems transaction did not reach blockchain yet. Getting stuck in peatio.

F, [2018-03-21T22:34:37.329391 #13850] FATAL -- : undefined local variable or method currency' for #<Worker::WithdrawCoin:0x0056156223f398> (NameError) /home/deploy/peatio/current/app/models/worker/withdraw_coin.rb:20:inblock in process'

**Comment by auvilink** [comment]
I am trying another withdraw and will report back

**Comment by auvilink** [comment]
![almost done](https://user-images.githubusercontent.com/13460230/37801413-c5100264-2de3-11e8-97ad-d76e01502275.jpeg)

translation missing: en.admin.withdraws.satoshis.update.notice

Another withdraw attempt, failed at "almost done" status

**Comment by mrtass** [comment]
can u see the withdraw request inn the admin panel ? try and if so approve it manually

**Comment by mrtass** [comment]
poat ur bitcoin.conf here as well and ur currency.yml

**Comment by auvilink** [comment]
can u see the withdraw request inn the admin panel ? try and if so approve it manually

Yese, I saw withdraw request in the admin panel and did manually approve it, then it becomes "almost done"

**Comment by auvilink** [comment]
bitcoin.conf

server=1
daemon=1

# If run on the test network instead of the real bitcoin network
#testnet=1

prune = 5000

# You must set rpcuser and rpcpassword to secure the JSON-RPC api
# Please make rpcpassword to something secure, `5gKAgrJv8CQr2CGUhjVbBFLSj29HnE6YGXvfykHJzS3k` for example.
# Listen for JSON-RPC connections on <port> (default: 8332 or testnet: 18332)
rpcuser=xx
rpcpassword=xxxx
rpcport=18332

# Notify when receiving coins
walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"satoshi"}'

**Comment by mrtass** [comment]
what about that address : xxxxxxx have u obfuscated it on purpose?

**Comment by auvilink** [comment]
what about that address : xxxxxxx have u obfuscated it on purpose?
Yes, the rpcuser: rpcpassword are the same in currencies.yml and bitcoin.conf

**Comment by auvilink** [comment]
accounts:
-
address: xxxxxxxxx

This is just the bitcoin wallet address on my mac (on local machine, not on the server), Could this be the issue?

**Comment by mrtass** [comment]
tey to use a complicated password 
and disable ufw

and restart all daemons

**Comment by auvilink** [comment]
ok. Let me disable all ufw and restart all daemons.

I just don't understand the error : 

F, [2018-03-22T22:13:38.334197 #13850] FATAL -- : undefined local variable or method currency' for #<Worker::WithdrawCoin:0x0056156223f398> (NameError)

**Comment by mrtass** [comment]
can u as well tailf production.log

**Comment by auvilink** [comment]
tailf production.log 
I, [2018-03-22T22:13:38.585129 #14692]  INFO -- : Started GET "/admin/withdraws/satoshis/3" for 172.56.17.129 at 2018-03-22 22:13:38 +0000
I, [2018-03-22T22:13:38.586126 #14692]  INFO -- : Processing by Admin::Withdraws::SatoshisController#show as HTML
I, [2018-03-22T22:13:38.586167 #14692]  INFO -- :   Parameters: {"id"=>"3"}
I, [2018-03-22T22:13:38.604959 #14692]  INFO -- :   Rendered shared/admin/_member.html.slim (4.0ms)
I, [2018-03-22T22:13:38.607312 #14692]  INFO -- :   Rendered shared/admin/_account.html.slim (1.6ms)
I, [2018-03-22T22:13:38.607375 #14692]  INFO -- :   Rendered admin/withdraws/satoshis/show.html.slim within layouts/admin (9.6ms)
I, [2018-03-22T22:13:38.615160 #14692]  INFO -- :   Rendered shared/_flash.slim (0.1ms)
I, [2018-03-22T22:13:38.615317 #14692]  INFO -- : Completed 200 OK in 29ms (Views: 16.5ms | ActiveRecord: 1.9ms)
I, [2018-03-22T22:13:41.055157 #13905]  INFO -- :

**Comment by auvilink** [comment]
OK, after disabling all firewall and restart all daemons, it now says "Processing" for the last two hours in the admin panel

![processing](https://user-images.githubusercontent.com/13460230/37805397-36f350c6-2df7-11e8-9a58-b99c2e614dd7.jpeg)

**Comment by mrtass** [comment]
cool now u can check ur transaction on blockchain

**Comment by auvilink** [comment]
I think it still get stuck somewhere in peatio.

Can't find the transaction on blockchain.

**Comment by mrtass** [comment]
search ur debug.log for that transaction 
maybe ur fees are too low

**Comment by auvilink** [comment]
Thanks @mrtass .

I retried withdraw. Still no go, says "processing"
The fee is not too low, actually I see much lower fees with some of my other transactions (not peatio related).

**The problem seems that the withdraw never gets to the bitcoind server** (which is the same server that peatio runs on). so there is no information about the withdraw in /bitcoin/debug.log.  

Deposit on the other hand, reaches the bitcoind server fast and shows in the /bitcoin/debug.log

**Comment by auvilink** [comment]
Thanks @mrtass 
Does that mean you have no issue withdraw btc?
BTW, How about ETH deposit and withdraw?

If you have no issue with both, I'll try to do a  fresh install on another server.

**Comment by muhammednagy** [comment]
hey guys 
it means that peatio tried to connect to bitcoin server and for some reason it couldn't do the transaction 
soo check your firewalls 
check rpcallowip in bitcoin.conf
check the ip
check the username and password

**Comment by auvilink** [comment]
@muhammednagy @mrtass 
Thanks.

The bitcoin server and the peatio server is the same one.
Do I still need the rpcallowip in bitcoin.conf?
All firewall are disabled.
Anyway, I'll try to do a new fresh install using your instruction here:

https://github.com/InfraexDev/peatio/blob/stable/doc/deploy-production-server.md

I suppose this instruction is up-to-date, right?

Both Bitcoin and ETH deposit/withdraw should work fine, right?

Thanks again.

**Comment by mrtass** [comment]
try these in bitcoin.conf
rpcbind=127.0.0.1
rpcport=18332
rpcallowip=127.0.0.1

**Comment by mrtass** [comment]
can u post ur /etc/hosts file as well

**Comment by auvilink** [comment]
@mrtass 

127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

Thanks.

**Comment by mrtass** [comment]
open gitter i sent u my ip server to test

**Comment by auvilink** [comment]
ok, I just opened gitter

**Comment by muhammednagy** [comment]
i will close it okay?

**Comment by muhammednagy** [comment]
it isn't a peatio issue anyways it's wallet connectivity issue
