### ISSUE TITLE
BTC deposit not showing in member account of peatio

### ISSUE THREAD

**Issue by nantestdevoloper** [InfraexDev/peatio#67]
deposited 0.0001 btc in peatio desposit address account .Bitcoind server is upto date.

but still btc balance not showing in account balance of peatio.
I checked for the logs for deposit_coins.output

getting error
I, [2018-04-03T16:03:21.537211 #22813]  INFO -- : Received: {"payment_address_id":43,"currency":"btc","locale":"en"}
I, [2018-04-03T16:03:30.201166 #22813]  INFO -- : Received: {"payment_address_id":44,"currency":"eth","locale":"en"}
/home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:55:in `join': Connection-level error: CONNECTION_FORCED - broker forced connection closure with reason 'shutdown' (Bunny::ConnectionForced)
  from /home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:55:in `block in join'
  from /home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:55:in `each'
  from /home/.rvm/gems/ruby-2.2.1/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:55:in `join'
  from /home/peatio/lib/daemons/amqp_daemon.rb:81:in `<top (required)>'
  from /home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `load'
  from /home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:203:in `start_load'
  from /home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/application.rb:298:in `start'
  from /home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
  from /home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons.rb:147:in `block in run'
  from /home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
  from /home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
  from /home/.rvm/gems/ruby-2.2.1/gems/daemons-1.1.9/lib/daemons.rb:146:in `run'
  from /home/.rvm/gems/ruby-2.2.1/gems/daemons-rails-1.2.1/lib/daemons/rails.rb:16:in `run'
  from lib/daemons/deposit_coin_ctl:11:in `<main>'

Below are my bitcoin.conf  setup
server=1
daemon=1

# If run on the test network instead of the real bitcoin network
#testnet=1

# You must set rpcuser and rpcpassword to secure the JSON-RPC api
# Please make rpcpassword to something secure, `5gKAgrJv8CQr2CGUhjVbBFLSj29HnE6YGXvfykHJzS3k` for example.
# Listen for JSON-RPC connections on <port> (default: 8332 or testnet: 18332)
rpcuser=test
rpcpassword=pass_some_hexa
rpcport=8332

# Notify when receiving coins
walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"satoshi"}'

peatio and bitcoind are running on same server local Ubuntu.
daemons are running as I  checked status.
Do I need to change 
walletnotify=/usr/local/sbin/rabbitmqadmin publish routing_key=peatio.deposit.coin payload='{"txid":"%s", "channel_key":"satoshi"}'
for local system.

please help me to understand the problem I am new to peatio. trying to understand system as well

**Comment by nantestdevoloper** [comment]
closing this as of now I got my btc deposited in peatio wallet.

**Comment by openbooknoobdeveloper** [comment]
@nantestdevoloper  did u fix this my friend? I am having the same issue, thank you.

**Comment by nantestdevoloper** [comment]
@openbooknoobdeveloper  yes, for this,all daemons should up and Is your bitcoind server is upto date?

**Comment by openbooknoobdeveloper** [comment]
@nantestdevoloper  yes it is, I am using the local in my machine not the one from the docker

**Comment by nantestdevoloper** [comment]
@openbooknoobdeveloper  what exactly problem you are facing not able to deposit coin or address not generating?
if your bitcoind is upto date and daemons are up ,it will automatically generate address and you can deposit coins to account .
