### ISSUE TITLE
Pusher Error

### ISSUE THREAD

**Issue by vitorgamer58** [InfraexDev/peatio#69]
but i get this erro on webconsole

`Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":1006,"message":"Connection interrupted (0)"}}}`

**Comment by muhammednagy** [comment]
are you using the main pusher data center?

**Comment by vitorgamer58** [comment]
yes

**Comment by muhammednagy** [comment]
Can you try to setup slanger and try?
i don't have much experience with pusher because i've never used it

**Comment by vitorgamer58** [comment]
I'll try, thank you.
