### ISSUE TITLE
Withdrawal Coins Rejected Within Seconds

### ISSUE THREAD

**Issue by hostsleek** [InfraexDev/peatio#73]
When sending coins. BTC or LTC to users within the exchange they get rejected in seconds.

How can i fix this.

Thanks

**Comment by muhammednagy** [comment]
that's normal 
if you want to allow this 
it's in app/models/concerns/withdraws/coinable.rb
this line 
      result = CoinRPC[currency].validateaddress(fund_uid)

**Comment by hostsleek** [comment]
I removed the below lines and stiill getting rejected

elsif (result[:ismine] == true) || PaymentAddress.find_by_address(fund_uid)
        Rails.logger.info "#{self.class.name}##{id} uses hot wallet address: #{fund_uid.inspect}"
        accept
        save!

**Comment by hostsleek** [comment]
Issue solved.. Thanks Mohammed.
