### ISSUE TITLE
ETH DEPOSIT APPEARS STUCK

### ISSUE THREAD

**Issue by hostsleek** [InfraexDev/peatio#82]
I have setup ETH on testnet and i am able to generate address without issues. I notice the error below when depositing..

See Error logs below.

I can't see any problem on this line --> /home/deploy/peatio/current/app/models/worker/deposit_coin.rb:21:in `process'

> I, [2018-04-23T15:00:11.274578 #21798]  INFO -- : Received: {"payment_address_id":17,"currency":"eth","locale":"en"}
F, [2018-04-23T15:00:11.276551 #21798] FATAL -- : ======= DEBUG ETH ====
F, [2018-04-23T15:00:11.276607 #21798] FATAL -- : [""]
F, [2018-04-23T15:00:11.276679 #21798] FATAL -- : -----------------------------
F, [2018-04-23T15:00:14.262953 #21798] FATAL -- : {"jsonrpc"=>"2.0", "id"=>"1", "result"=>"0xe114a80918005757212b916b921035465af700ac"}
F, [2018-04-23T15:00:14.263114 #21798] FATAL -- : -----------------------------
I, [2018-04-23T15:02:52.561618 #21798]  INFO -- : Received: {"txid":"0x63c75825e400258a850e9b894fc3e860ac826e9a5ada20b39ba17da2cac497bd","channel_key":"ether","locale":"en"}
F, [2018-04-23T15:02:52.561763 #21798] FATAL -- : ============= DEBUG PROCESS DEPOSIT ========================
F, [2018-04-23T15:02:52.561801 #21798] FATAL -- : ------------ payload ------------------
F, [2018-04-23T15:02:52.561823 #21798] FATAL -- : {"txid"=>"0x63c75825e400258a850e9b894fc3e860ac826e9a5ada20b39ba17da2cac497bd", "channel_key"=>"ether", "locale"=>"en"}
F, [2018-04-23T15:02:52.561856 #21798] FATAL -- : ------------- metadata --------------------------
F, [2018-04-23T15:02:52.561874 #21798] FATAL -- : {:content_type=>"application/octet-stream", :delivery_mode=>2, :priority=>0}
F, [2018-04-23T15:02:52.561933 #21798] FATAL -- : --------------------------------------
F, [2018-04-23T15:02:53.066359 #21798] FATAL -- : ======= DEBUG ETH ====
F, [2018-04-23T15:02:53.066559 #21798] FATAL -- : ["0x63c75825e400258a850e9b894fc3e860ac826e9a5ada20b39ba17da2cac497bd"]
F, [2018-04-23T15:02:53.066639 #21798] FATAL -- : -----------------------------
F, [2018-04-23T15:02:53.069256 #21798] FATAL -- : {"jsonrpc"=>"2.0", "id"=>"1", "result"=>nil}
F, [2018-04-23T15:02:53.069372 #21798] FATAL -- : -----------------------------
F, [2018-04-23T15:02:53.069489 #21798] FATAL -- : undefined method `symbolize_keys!' for nil:NilClass (NoMethodError)
/home/deploy/peatio/current/app/models/worker/deposit_coin1.rb:21:in `process'
/home/deploy/peatio/current/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/channel.rb:1672:in `block in handle_frameset'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `call'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:84:in `block (2 levels) in run_loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:80:in `block in run_loop'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `catch'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer_work_pool.rb:79:in `run_loop'
F, [2018-04-23T15:02:53.069697 #21798] FATAL -- : /home/deploy/peatio/current/app/models/worker/deposit_coin1.rb:21:in `process'
/home/deploy/peatio/current/lib/daemons/amqp_daemon.rb:61:in `block (2 levels) in <top (required)>'
/home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/bunny-1.2.1/lib/bunny/consumer.rb:56:in `call'

**Comment by muhammednagy** [comment]
that's definitely a syncing problem
so we try to get a transaction info using the txid but it replies with nil

**Comment by hostsleek** [comment]
SYNCING Problem with the ETH NODE.

Any fix or advice for this?

**Comment by muhammednagy** [comment]
yeah 
use latest version of geth 
geth --fast --cache=1024  --rpc  --rpcaddr=0.0.0.0 --rpcport=8545  --rpcapi eth,personal,net,web3,db

**Comment by hostsleek** [comment]
Thanks Muhammednagy... You the MAN..

Will update this page once the ETH is done syncing and deposits works fine.

Thanks for your assistance.

**Comment by hostsleek** [comment]
I get the below message when starting filter service.. 

Doing this i was able to update the deposit balance on petio
#Net::HTTP.post_form(URI.parse('http://dev2..io/webhooks/eth'), {'type'=>'transaction', 'hash'=>"0x51ac4b6fa1d5814e1abcc36669dcd53fb9c82a85c42a0af4acaf08fd7cedf19b"})

What could be wrong.. any idea

`sudo: unable to resolve host eth..io
● filter.service - filter
   Loaded: loaded (/etc/systemd/system/filter.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-04-25 06:43:27 EDT; 13s ago
  Process: 26661 ExecStart=/usr/bin/ruby /home/ubuntu/service.rb (code=exited, status=1/FAILURE)
 Main PID: 26661 (code=exited, status=1/FAILURE)

Apr 25 06:43:27 eth..io systemd[1]: Started filter.
Apr 25 06:43:27 eth..io ruby[26661]: /var/lib/gems/2.3.0/gems/web3-0.1.0/lib/web3.rb:53:in `do_request': In response to eth_getBlockByNumber request, JSON-RPC endpoint returne
Apr 25 06:43:27 eth..io ruby[26661]:         from /var/lib/gems/2.3.0/gems/web3-0.1.0/lib/generated_web3_methods.rb:138:in `eth_getBlockByNumber'
Apr 25 06:43:27 eth.io ruby[26661]:         from /home/ubuntu/service.rb:6:in `<main>'
Apr 25 06:43:27 eth..io systemd[1]: filter.service: Main process exited, code=exited, status=1/FAILURE
Apr 25 06:43:27 eth..io systemd[1]: filter.service: Unit entered failed state.
Apr 25 06:43:27 eth..io systemd[1]: filter.service: Failed with result 'exit-code'.
Apr 25 06:43:34 eth..io systemd[1]: Stopped filter.
`

**Comment by ninoara** [comment]
Please any update? I am facing the same problem.
