### ISSUE TITLE
trade screen - never stop loading

### ISSUE THREAD

**Issue by gitgut1000** [InfraexDev/peatio#84]
trade screen - graph never stop loading

browser debug shows error 500 from this call
http://localhost:3000/api/v2/k_with_pending_trades.json?market=skrtundx&limit=768&period=60&trade_id=1 

any idea?

**Comment by muhammednagy** [comment]
you need orders in the timeframe you are wanting to display 

if you posted orders in last 5 mins but not in last hour 
1h won't work
