### ISSUE TITLE
Ethereum Security Issue

### ISSUE THREAD

**Issue by hostsleek** [InfraexDev/peatio#89]
I notice whenever i transfer coins to my ETH acccount.. When i initiate a transfer out.. All remaining funds are sent to this ETH adress 0x6Ef57BE1168628A2bD6c5788322A41265084408a

What firewall security or measures do you take to protect your Eth coins from being stolen.

Regards

**Comment by muhammednagy** [comment]
i have all the ports closed in a firewall 
i assume the man who installs ethereum understands

**Comment by muhammednagy** [comment]
also if you checked the nginx config you will notice that i have commented out password protected access

**Comment by hostsleek** [comment]
I have all ports also closed in a firewall and allow only peatio app access to port 80 and 8545..

But Withdrawal and deposit wont work if the above firewall is set

**Comment by muhammednagy** [comment]
no you are leaving the default rpc port open  8545
that's how he connected 
check ethereum issues about that
