### ISSUE TITLE
Cannot Sign In

### ISSUE THREAD

**Issue by appsdev9** [InfraexDev/peatio#96]
Hi,

Tried to logon via localhost:3000/signin with the below credentials but failed. What is the correct admin username and password? Thanks.

username: admin@peatio.dev
password: Pass@word8
 
![sign-in-error](https://user-images.githubusercontent.com/7036716/40578258-670d3e8c-6143-11e8-846a-f7194dd06287.png)

**Comment by muhammednagy** [comment]
please try to do bundle exec rake db:seed

**Comment by appsdev9** [comment]
Can now logon successfully. Thanks, muhammednagy
